### ISSUE TITLE
Iteration number in f(i, x)

### ISSUE THREAD

**Issue by pierrelux** [gehring/fax#20]
In ``two_phase_solver``, the ``param_func`` argument must return a binary function of the form ``f(i,x)`` where ``i`` is the iteration number. So far, I haven't had a case yet where I had a function/operator depending on ``i`` and always end up writing a lambda to get a binary function. https://github.com/gehring/fax/blob/5b54a85d7d473aedb5fb161a6e47ad4073b9647e/fax/implicit/twophase.py#L84-L85

Could we perhaps handle both cases for ``param_func``? Namely, to detect if ``f`` is unary or binary and handle both cases seamlessly?

**Comment by gehring** [comment]
I agree. This is remnants of when we were trying to match the function signature used by `jax.experimental.optimizers`. Given the new `jax.experimental.stax` API, this extra iteration number provides even fewer benefits than it did originally.

**Comment by pierrelux** [comment]
I'm not up-to-date with the optimizer interface. In general, if the user really needs the iteration number, I guess that she can add that information to the state variable.
