### ISSUE TITLE
A Lagrangian Method for Inverse Problems in Reinforcement Learning

### ISSUE THREAD

**Issue by manuel-delverme** [gehring/fax#38]
the implementation of $(Title) paper redirects (http://people.csail.mit.edu/gehring/) to this repo, is there a test case for the paper experimens?

**Comment by gehring** [comment]
What do you mean by test case in this context? Are you asking if some of the tests in fax run parts of the experiments?

**Comment by manuel-delverme** [comment]
If I want to reproduce the paper experiments, how can i do that?

**Comment by gehring** [comment]
@pierrelux Is there anything preventing us from making the repo with the experiment scripts public?

**Comment by pierrelux** [comment]
The polytope experiments are part of the tests in https://github.com/gehring/fax/blob/63606eb7e509cfee43107634696351da98eee9b1/fax/constrained/constrained_test.py#L118 

For the LQR experiments, it's in a different repo. I would keep it out of Fax.

**Comment by gehring** [comment]
Could we switch the repo containing the LQR experiments from private to public?

**Comment by pierrelux** [comment]
Sure I think you that this code is in your repo. Let's sync up 1:1

**Comment by gehring** [comment]
@manuel-delverme See [this repo](https://github.com/pierrelux/lagrangian-rl) for the experiment code (and other miscellaneous code that was related to that project at some point or another).
